[package]
name = "sns-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_bytes.workspace = true
candid.workspace = true
humantime = "2.1.0"
regex = "1.10.5"
web-time.workspace = true