name: Deploy hot-or-not-ssr app on global-constants change
permissions:
  contents: read
on:
  push:
    branches:
      - master
    paths:
      - "global-constants/**"
      - ".github/workflows/deploy-dispatch-ssr.yml"

jobs:
  deploy-to-hot-or-not-web-leptos-ssr:
    runs-on: ubuntu-latest
    steps:
      - name: Short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Dispatch event to hot-or-not-web-leptos-ssr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.LIMITS_CHANGE_DISPATCH_TOKEN }}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: 'dolr-ai',
              repo: 'hot-or-not-web-leptos-ssr',
              event_type: 'global-constants-change',
              client_payload: {"commit_hash": "${{ env.SHORT_SHA }}" }
            })

  deploy-to-yral-backend-cloudflare-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Dispatch event to yral-backend-cloudflare-workers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.LIMITS_CHANGE_DISPATCH_TOKEN }}
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: 'dolr-ai',
              repo: 'yral-backend-cloudflare-workers',
              event_type: 'global-constants-change',
              client_payload: {"commit_hash": "${{ env.SHORT_SHA }}" }
            })
